#!/usr/bin/env bash

# Получаем абсолютный путь к директории, где лежит скрипт
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
# PROJECT_ROOT - корень репозитория
PROJECT_ROOT=$(dirname "$SCRIPT_DIR")

# Добавляем каталог src в PYTHONPATH для доступа к пакетам
export PYTHONPATH="$PROJECT_ROOT/src:$PYTHONPATH"

# Запускаем Python-модуль, передавая ему все аргументы
python -m qiki_dtmp.tools.qiki_docgen "$@"
